# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecpow2 <- function(base, exp) {
    .Call(`_DiveR_vecpow2`, base, exp)
}

vecdiv <- function(num, denum) {
    .Call(`_DiveR_vecdiv`, num, denum)
}

#' half_life
#' 
#' @param period period in minute for the compartment.
#' @param time time at which user want the load of nitrogen
#' 
#' @examples 
#' cpp_half_life(period = 1, time = c(1,2))
#' 
#' @rdname half_life
#' @export
cpp_half_life <- function(period, time) {
    .Call(`_DiveR_cpp_half_life`, period, time)
}

cpp_haldane_desat <- function(dtcurve, comp, Scomp, depths, ppn2_ini = 0.791, bpal_speed = 6.0) {
    .Call(`_DiveR_cpp_haldane_desat`, dtcurve, comp, Scomp, depths, ppn2_ini, bpal_speed)
}

insertCell <- function(x, n) {
    .Call(`_DiveR_insertCell`, x, n)
}

