# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecpow2 <- function(base, exp) {
    .Call(`_DiveR_vecpow2`, base, exp)
}

vecdiv <- function(num, denum) {
    .Call(`_DiveR_vecdiv`, num, denum)
}

cpp_half_life <- function(period, time) {
    .Call(`_DiveR_cpp_half_life`, period, time)
}

cpp_haldane_desat <- function(dtcurve, comp, Scomp, depths) {
    .Call(`_DiveR_cpp_haldane_desat`, dtcurve, comp, Scomp, depths)
}

insertCell <- function(x, n) {
    .Call(`_DiveR_insertCell`, x, n)
}

cpp_insertRow <- function(df, newrow, r) {
    .Call(`_DiveR_cpp_insertRow`, df, newrow, r)
}

